version: "3.7"

services:
    # image project
    app:
        image: laravel-10-app
        container_name: laravel-10-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel
        environment:
            CONTAINER_ROLE: app
    # vite
    vite:
        image: laravel-10-app
        container_name: laravel-10-app-vite
        restart: unless-stopped
        ports:
            - 5173:5173
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - app
        networks:
            - laravel
        environment:
            CONTAINER_ROLE: vite
    # fila
    fila:
        image: laravel-10-app
        container_name: laravel-10-app-fila
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - app
            - redis
        environment:
            CONTAINER_ROLE: fila
        networks:
            - laravel
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:5.7.22
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_USER: ${DB_USERNAME:-root}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel
        volumes:
            - redis:/data

networks:
    laravel:
        driver: bridge
volumes:
  redis:
    driver: "local"
